@startuml
hide empty members

' 天気

abstract class Weather {
    - time : Date
    - temperature : double
    - windSpeed : double
    - chanceOfRain : double
}

class Sunny {
}
class Cloudy {
}
class Rain {
    - precipitation : double
}
class snow {
}
class Typhoon {
    - Location - int[]
    - Pressure - int
}


' 警報

abstract class Warning {
    - name : String
}

class WindWarning {

}
class HeavyRainWarning {

}
class ThunderstormWarning {

}
class HeavySnowWarning {

}

Weather <|-- Sunny
Weather <|-- Cloudy
Cloudy <|-- Rain
Cloudy <|-- snow
Rain <|-- Typhoon

Warning <|-- WindWarning
Warning <|-- HeavyRainWarning
Warning <|-- ThunderstormWarning
Warning <|-- HeavySnowWarning

@enduml